"""empty message

Revision ID: 852710913f10
Revises: bf289e2d02c5
Create Date: 2019-06-30 10:27:53.475786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852710913f10'
down_revision = 'bf289e2d02c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
